import type { Trade } from '../src/db/schema'
import type { TradeMetrics } from '../src/metrics'
import type { Summary } from '../src/summary'

const metrics: TradeMetrics = {
  closed: 2,
  winRate: 50,
  avgReturnPct: 2.5,
  avgHoldHours: 36,
  profitFactor: 2,
  realizedPl: 10,
}
export const emptyMetrics: TradeMetrics = {
  closed: 0,
  winRate: null,
  avgReturnPct: null,
  avgHoldHours: null,
  profitFactor: null,
  realizedPl: 0,
}
const costs = {
  subscriptionUsd: 100,
  platformUsd: 2.5,
  xPostsUsd: 0.03,
  apiEquivalentUsd: 3,
  totalUsd: 102.53,
}

export const closed: Trade = {
  id: 1,
  fund: 'social',
  symbol: 'BTC/USD',
  assetClass: 'crypto',
  notional: 100,
  qty: 0.002,
  limitPrice: null,
  expiresAt: null,
  entryPrice: 50000,
  stop: 45000,
  target: 60000,
  trailPct: null,
  entryStop: null,
  liquidate: false,
  horizon: '2 weeks',
  reason: 'r',
  status: 'closed',
  orderId: null,
  closeOrderId: null,
  exitPrice: 55000,
  exitReason: '<b>thesis</b> broke',
  openedAt: '2026-09-01T14:00:00.000Z',
  closedAt: '2026-09-03T15:00:00.000Z',
}

export function makeSummary(overrides: Partial<Summary> = {}): Summary {
  return {
    generatedAt: '2026-09-15T12:00:00.000Z',
    equity: 1100,
    cash: 700,
    horizon: '1M',
    horizons: [
      { label: '1D', pct: 1, baseline: 1089.11 },
      { label: '1W', pct: -2, baseline: 1122.45 },
      { label: '1M', pct: 10, baseline: 1000 },
      { label: '3M', pct: null, baseline: null },
      { label: 'ALL', pct: 22, baseline: 901.64 },
    ],
    series: [
      { takenAt: 'a', equity: 1000 },
      { takenAt: 'b', equity: 1100 },
    ],
    charts: {
      '1D': [{ takenAt: 'b', equity: 1100 }],
      '1W': [
        { takenAt: 'a', equity: 1000 },
        { takenAt: 'b', equity: 1100 },
      ],
      '1M': [
        { takenAt: 'a', equity: 1000 },
        { takenAt: 'b', equity: 1100 },
      ],
      '3M': [],
      ALL: [
        { takenAt: 'a', equity: 1000 },
        { takenAt: 'b', equity: 1100 },
      ],
    },
    holdings: [
      {
        fund: 'social',
        symbol: 'AAPL',
        qty: 0.5,
        value: 110,
        unrealizedPl: 10,
        entryPrice: 200,
        currentPrice: 220,
        stop: 180,
        target: 240,
        trailPct: null,
        entryStop: null,
        horizon: '2 weeks',
        reason: '<script>alert(1)</script>',
        openedAt: '2026-08-20T14:00:00.000Z',
      },
      {
        fund: 'social',
        symbol: 'BTC/USD',
        qty: 2,
        value: 50,
        unrealizedPl: -1,
        entryPrice: 25,
        currentPrice: 24.5,
        stop: 20,
        target: 30,
        trailPct: null,
        entryStop: null,
        horizon: '1 week',
        reason: 'plain',
        openedAt: '2026-08-20T14:00:00.000Z',
      },
    ],
    queued: [],
    funds: [
      {
        id: 'social',
        name: 'Social & signal',
        status: 'active',
        mandate: 'Watch <reviews>',
        capUsd: 550,
        capitalUsd: 550,
        highWaterUsd: 550,
        drawdownPct: 0,
        tier: 'full',
        rescues: 0,
        deployedUsd: 175,
        unrealizedPl: 9,
        openCount: 2,
        metrics,
      },
      {
        id: 'old',
        name: 'Old',
        status: 'retired',
        mandate: 'm',
        capUsd: 0,
        capitalUsd: 0,
        highWaterUsd: 0,
        drawdownPct: 0,
        tier: 'shut',
        rescues: 0,
        deployedUsd: 0,
        unrealizedPl: 0,
        openCount: 0,
        metrics: emptyMetrics,
      },
    ],
    metrics,
    money: {
      subscriptionUsd: 200,
      monthlyCostUsd: 205,
      runwayMonths: 0.5,
      allTime: { returnUsd: 210, costsUsd: 107.5, netUsd: 102.5 },
      month: {
        startEquity: 1000,
        returnUsd: 100,
        returnPct: 10,
        daysLeft: 16,
        costs,
        netUsd: -2.53,
        surviving: false,
      },
      window: {
        costs,
        series: [
          { takenAt: 'a', returnUsd: 0, costUsd: 0 },
          { takenAt: 'b', returnUsd: 100, costUsd: 3 },
        ],
      },
      payouts: { fraction: 0.2, totalUsd: 10, capitalAfterPayoutsUsd: 1090, history: [] },
    },
    closedTrades: [closed],
    closedPage: { page: 1, pages: 1 },
    lastRun: { finishedAt: '2026-09-14T00:05:00.000Z', summary: 'Bought <AAPL>', costUsd: 2 },
    ...overrides,
  }
}
